topicTagDict = {
    'AF_BUILDING'           : ['CITY'],
    'AF_CULTURAL_ASSET'     : ['HISTORY_ANCIENT','HISTORY_EARLY','TOUR'],
    'AF_MUSICAL_INSTRUMENT' : ['ART_MUSIC'],
    'AF_ROAD'               : ['TRAFFIC'],
    'AF_TRANSPORT'          : ['TRAFFIC'],
    'AF_WARES'              : ['DEFAULT'],
    'AF_WEAPON'             : ['MILITARY'],
    'AF_WORKS'              : ['DEFAULT'],
    'AFW_ART_CRAFT'         : ['ART'],
    'AFW_DOCUMENT'          : ['ACADEMIC'],
    'AFW_MUSIC'             : ['ART_MUSIC'],
    'AFW_PERFORMANCE'       : ['ART'],
    'AFW_VIDEO'             : ['MEDIA'],
    'AM_AMPHIBIA'           : ['NATURE_GREEN'],
    'AM_BIRD'               : ['NATURE_GREEN'],
    'AM_FISH'               : ['NATURE_BLUE'],
    'AM_INSECT'             : ['NATURE_GREEN'],
    'AM_MAMMALIA'           : ['NATURE_GREEN'],
    'AM_OTHERS'             : ['SCIENCE_BIO'],
    'AM_PART'               : ['SCIENCE_BIO'],
    'AM_REPTILIA'           : ['NATURE_GREEN'],
    'AM_TYPE'               : ['SCIENCE_BIO'],
    'CV_BUILDING_TYPE'      : ['HISTORY_ANCIENT', 'HISTORY_EARLY'],
    'CV_CLOTHING'           : ['PEOPLE'],
    'CV_CURRENCY'           : ['MONEY'],
    'CV_DRINK'              : ['FOOD'],
    'CV_FOOD'               : ['FOOD'],
    'CV_FOOD_STYLE'         : ['FOOD'],
    'CV_FUNDS'              : ['MONEY'],
    'CV_LANGUAGE'           : ['DEFAULT'],
    'CV_LAW'                : ['POLICY'],
    'CV_NAME'               : ['HISTORY_ANCIENT'],
    'CV_OCCUPATION'         : ['PEOPLE'],
    'CV_POLICY'             : ['POLICY'],
    'CV_POSITION'           : ['PEOPLE'],
    'CV_PRIZE'              : ['POLICY'],
    'CV_RELATION'           : ['PEOPLE'],
    'CV_SPORTS'             : ['SPORTS'],
    'CV_SPORTS_INST'        : ['SPORTS'],
    'CV_TAX'                : ['POLICY', 'MONEY'],
    'CV_TRIBE'              : ['HISTORY_ANCIENT'],
    'DT_DAY'                : ['DEFAULT', 'TIME'],
    'DT_DURATION'           : ['TIME'],
    'DT_DYNASTY'            : ['HISTORY_ANCIENT'],
    'DT_GEOAGE'             : ['HISTORY_ANCIENT'],
    'DT_MONTH'              : ['TIME'],
    'DT_OTHERS'             : ['TIME'],
    'DT_SEASON'             : ['DEFAULT'],
    'DT_YEAR'               : ['HISTORY_ANCIENT', 'HISTORY_EARLY', 'TIME'],
    'EV_ACTIVITY'           : ['HISTORY_EARLY', 'POLICY'],
    'EV_FESTIVAL'           : ['TOUR'],
    'EV_OTHERS'             : ['HISTORY_EARLY'],
    'EV_SPORTS'             : ['SPORTS', 'TOUR'],
    'EV_WAR_REVOLUTION'     : ['HISTORY_EARLY', 'MILITARY'],
    'FD_ART'                : ['ART', 'ART_MUSIC'],
    'FD_MEDICINE'           : ['MEDICAL'],
    'FD_OTHERS'             : ['ACADEMIC'],
    'FD_PHILOSOPHY'         : ['ACADEMIC'],
    'FD_SCIENCE'            : ['SCIENCE_CHEM', 'SCIENCE_PHY', 'SCIENCE_BIO', 'SCIENCE_GEO', 'IT'],
    'FD_SOCIAL_SCIENCE'     : ['POLICY'],
    'LC_OTHERS'             : ['DEFAULT'],
    'LC_SPACE'              : ['SCIENCE_GEO', 'SPACE'],
    'LC_TOUR'               : ['TOUR'],
    'LCG_BAY'               : ['NATURE_BLUE'],
    'LCG_CONTINENT'         : ['NATURE_BLUE'],
    'LCG_ISLAND'            : ['TOUR'],
    'LCG_MOUNTAIN'          : ['NATURE_GREEN'],
    'LCG_OCEAN'             : ['NATURE_BLUE', 'TOUR'],
    'LCG_RIVER'             : ['NATURE_BLUE', 'TOUR'],
    'LCP_CAPITALCITY'       : ['CITY', 'TOUR'],
    'LCP_CITY'              : ['CITY', 'TOUR'],
    'LCP_COUNTRY'           : ['TOUR'],
    'LCP_COUNTY'            : ['DEFAULT'],
    'LCP_PROVINCE'          : ['DEFAULT'],
    'MT_CHEMICAL'           : ['SCIENCE_CHEM'],
    'MT_ELEMENT'            : ['SCIENCE_CHEM'],
    'MT_METAL'              : ['SCIENCE_CHEM'],
    'MT_ROCK'               : ['SCIENCE_GEO'],
    'OG_OTHERS'             : ['DEFAULT'],
    'OGG_ART'               : ['ART', 'ART_MUSIC'],
    'OGG_ECONOMY'           : ['MONEY'],
    'OGG_EDUCATION'         : ['EDUCATION', 'PEOPLE'],
    'OGG_FOOD'              : ['FOOD'],
    'OGG_HOTEL'             : ['TOUR'],
    'OGG_LAW'               : ['POLICY'],
    'OGG_LIBRARY'           : ['ACADEMIC'],
    'OGG_MEDIA'             : ['MEDIA'],
    'OGG_MEDICINE'          : ['MEDICAL'],
    'OGG_MILITARY'          : ['MILITARY'],
    'OGG_POLITICS'          : ['POLICY'],
    'OGG_RELIGION'          : ['ACADEMIC'],
    'OGG_SCIENCE'           : ['SCIENCE_PHY', 'SCIENCE_BIO', 'SCIENCE_CHEM', 'SCIENCE_GEO', 'IT'],
    'OGG_SPORTS'            : ['SPORTS'],
    'PS_NAME'               : ['DEFAULT'],
    'PT_FLOWER'             : ['COLORFUL'],
    'PT_FRUIT'              : ['COLORFUL', 'FOOD', 'FRUIT'],
    'PT_GRASS'              : ['NATURE_GREEN'],
    'PT_OTHERS'             : ['SCIENCE_BIO'],
    'PT_PART'               : ['SCIENCE_BIO'],
    'PT_TREE'               : ['NATURE_GREEN'],
    'PT_TYPE'               : ['SCIENCE_BIO'],
    'QT_AGE'                : ['NUMBER'],
    'QT_ALBUM'              : ['NUMBER'],
    'QT_CHANNEL'            : ['NUMBER', 'MEDIA'],
    'QT_COUNT'              : ['NUMBER'],
    'QT_LENGTH'             : ['NUMBER'],
    'QT_MAN_COUNT'          : ['NUMBER'],
    'QT_ORDER'              : ['NUMBER'],
    'QT_OTHERS'             : ['NUMBER'],
    'QT_PERCENTAGE'         : ['NUMBER', 'SCIENCE_CHEM'],
    'QT_PHONE'              : ['NUMBER'],
    'QT_PRICE'              : ['MONEY', 'NUMBER'],
    'QT_SIZE'               : ['NUMBER'],
    'QT_SPEED'              : ['NUMBER', 'SCIENCE_PHY'],
    'QT_SPORTS'             : ['NUMBER', 'SPORTS'],
    'QT_TEMPERATURE'        : ['NUMBER', 'SCIENCE_PHY', 'SCIENCE_CHEM'],
    'QT_VOLUME'             : ['NUMBER', 'SCIENCE_PHY', 'SCIENCE_CHEM'],
    'QT_WEIGHT'             : ['NUMBER', 'SCIENCE_PHY'],
    'QT_ZIPCODE'            : ['NUMBER'],
    'TI_DURATION'           : ['TIME'],
    'TI_HOUR'               : ['TIME'],
    'TI_MINUTE'             : ['TIME'],
    'TI_OTHERS'             : ['TIME'],
    'TI_SECOND'             : ['TIME'],
    'TM_CELL_TISSUE'        : ['SCIENCE_BIO'],
    'TM_CLIMATE'            : ['SCIENCE_GEO'],
    'TM_COLOR'              : ['COLORFUL'],
    'TM_DIRECTION'          : ['DEFAULT'],
    'TM_SHAPE'              : ['DEFAULT'],
    'TM_SPORTS'             : ['SPORTS'],
    'TMI_EMAIL'             : ['DEFAULT'],
    'TMI_HW'                : ['IT'],
    'TMI_MODEL'             : ['IT'],
    'TMI_PROJECT'           : ['IT'],
    'TMI_SERVICE'           : ['IT'],
    'TMI_SITE'              : ['DEFAULT'],
    'TMI_SW'                : ['IT'],
    'TMIG_GENRE'            : ['GAME'],
    'TMM_DISEASE'           : ['MEDICAL'],
    'TMM_DRUG'              : ['MEDICAL'],
    'TR_ART'                : ['ART', 'ART_MUSIC'],
    'TR_MEDICINE'           : ['MEDICAL'],
    'TR_OTHERS'             : ['ACADEMIC'],
    'TR_PHILOSOPHY'         : ['ACADEMIC'],
    'TR_SCIENCE'            : ['ACADEMIC', 'SCIENCE_PHY', 'SCIENCE_BIO', 'SCIENCE_CHEM', 'SCIENCE_GEO', 'IT'],
    'TR_SOCIAL_SCIENCE'     : ['ACADEMIC', 'POLICY']
}



topicWeightDict = {
    'ACADEMIC'          : 3,
    'ART'               : 3,
    'ART_MUSIC'         : 3,
    'CITY'              : 3,
    'COLORFUL'          : 2,
    'DEFAULT'           : 2,
    'EDUCATION'         : 3,
    'FOOD'              : 3,
    'FRUIT'             : 4,
    'GAME'              : 3,
    'HISTORY_ANCIENT'   : 3,
    'HISTORY_EARLY'     : 3,
    'IT'                : 4,
    'MEDIA'             : 3,
    'MEDICAL'           : 3,
    'MILITARY'          : 3,
    'MONEY'             : 3,
    'NATURE_BLUE'       : 3,
    'NATURE_GREEN'      : 3,
    'NUMBER'            : 1,
    'PEOPLE'            : 1,
    'POLICY'            : 3,
    'SCIENCE_CHEM'      : 3,
    'SCIENCE_PHY'       : 3,
    'SCIENCE_BIO'       : 3,
    'SCIENCE_CHEM'      : 3,
    'SCIENCE_GEO'       : 3,
    'SPACE'             : 3,
    'SPORTS'            : 3,
    'TIME'              : 1,
    'TOUR'              : 3,
    'TRAFFIC'           : 3
}